# Generated by Django 5.2.13 on 2026-04-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAddressTimeRangeThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_earliest', models.DateTimeField(blank=True, null=True)),
                ('start_latest', models.DateTimeField(blank=True, null=True)),
                ('end_earliest', models.DateTimeField(blank=True, null=True)),
                ('end_latest', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('entities', models.ManyToManyField(related_name='ranges', related_query_name='range', through='time_ranges.EntityAddressTimeRangeThrough', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entityaddresstimerangethrough',
            name='time_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_ranges.timerange'),
        ),
        migrations.AlterUniqueTogether(
            name='entityaddresstimerangethrough',
            unique_together={('entity', 'time_range', 'address')},
        ),
    ]
