# Generated by Django 4.2.1 on 2023-05-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0003_delete_event_alter_entity_options_and_more"),
        ("addresses", "0002_alter_address_number_alter_street_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="EntityAddressTimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="addresses.address"
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entities.entity"
                    ),
                ),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="time_ranges.timerange"
                    ),
                ),
            ],
        ),
    ]
