# Generated by Django 4.2.1 on 2023-05-21 00:19
from django.db import migrations
from django.utils import timezone
from dateutil.relativedelta import relativedelta


def create_allowed_ranges(apps, schema_editor):
    TimeRange = apps.get_model("time_ranges", "TimeRange")

    # Code to automatically create time range instances for allowed ranges in the database

    # Create time range instances based on allowed ranges
    year = timezone.datetime(1919, 1, 1, tzinfo=timezone.utc)
    # Add one year to the start date
    delta = relativedelta(years=1)

    allowed_ranges = [(str(year.year), year, year := year + delta) for i in range(0, 5)]

    for name, start_time, end_time in allowed_ranges:
        TimeRange.objects.get_or_create(
            name=name,
            defaults=dict(
                start_time=start_time,
                end_time=end_time,
            ),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("time_ranges", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_allowed_ranges, migrations.RunPython.noop),
    ]
