# Generated by Django 4.2.1 on 2023-05-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_ranges", "0002_add_census_ranges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timerange",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Name"),
        ),
    ]
