# Generated by Django 4.2.1 on 2023-05-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_address_number_alter_street_type"),
        ("entities", "0005_remove_business_snapshot_insert_and_more"),
        ("time_ranges", "0003_alter_timerange_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityAddressTimeRangeThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addresses.address",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entities.entity"
                    ),
                ),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="time_ranges.timerange"
                    ),
                ),
            ],
            options={
                "unique_together": {("entity", "time_range", "address")},
            },
        ),
        migrations.DeleteModel(
            name="EntityAddressTimeRange",
        ),
        migrations.AddField(
            model_name="timerange",
            name="entities",
            field=models.ManyToManyField(
                related_name="ranges",
                related_query_name="range",
                through="time_ranges.EntityAddressTimeRangeThrough",
                to="entities.entity",
            ),
        ),
    ]
