# Generated by Django 5.2.13 on 2026-04-20 05:11

import buildings.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_earliest', models.DateTimeField(blank=True, null=True)),
                ('start_latest', models.DateTimeField(blank=True, null=True)),
                ('end_earliest', models.DateTimeField(blank=True, null=True)),
                ('end_latest', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(verbose_name='ft'), default=list, size=2)),
                ('outline', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Outline')),
                ('meta', django_pydantic_field.fields.PydanticSchemaField(config=None, default=buildings.models.default_building_meta, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=buildings.models.BuildingMeta)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='addresses.address')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent building for sub-tenants / multi-unit addresses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_units', to='buildings.building')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
