# Generated by Django 4.1 on 2022-08-30 01:28

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("N", "North"), ("W", "West"), ("S", "South"), ("E", "East")],
                        max_length=1,
                        null=True,
                        verbose_name="Direction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("number", models.SmallIntegerField(verbose_name="Number")),
                ("floors", models.SmallIntegerField(default=1, verbose_name="Floors")),
                (
                    "size",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(verbose_name="ft"),
                        default=list,
                        size=2,
                    ),
                ),
                (
                    "outline",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Outline"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[("frame", "Frame"), ("brick", "Brick"), ("stucco", "Stucco")],
                        default="frame",
                        max_length=6,
                        verbose_name="Style",
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="buildings.street",
                    ),
                ),
            ],
        ),
    ]
