# Generated by Django 4.1 on 2022-09-04 02:43

import buildings.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="floors",
        ),
        migrations.RemoveField(
            model_name="building",
            name="style",
        ),
        migrations.AddField(
            model_name="building",
            name="meta",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default={"floors": 1, "style": "frame"},
                schema=buildings.models.BuildingMeta,
            ),
        ),
    ]
