# Generated by Django 4.1.7 on 2023-04-03 00:08

import buildings.models
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "__first__"),
        ("buildings", "0002_remove_building_floors_remove_building_style_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="number",
        ),
        migrations.RemoveField(
            model_name="building",
            name="street",
        ),
        migrations.AddField(
            model_name="building",
            name="address",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="addresses.address"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="building",
            name="meta",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None, schema=buildings.models.BuildingMeta
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.DeleteModel(
            name="Street",
        ),
    ]
