# Generated by Django 4.1.7 on 2023-04-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ave", "Avenue"),
                            ("blvd", "Boulevard"),
                            ("st", "Street"),
                            ("pl", "Place"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("N", "North"), ("W", "West"), ("S", "South"), ("E", "East")],
                        max_length=1,
                        null=True,
                        verbose_name="Direction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Number"),
                ),
                ("number_additional", models.CharField(max_length=120)),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="addresses.street"
                    ),
                ),
            ],
        ),
    ]
