# Generated by Django 5.2.13 on 2026-04-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('ave', 'Avenue'), ('blvd', 'Boulevard'), ('st', 'Street'), ('pl', 'Place')], default='st', max_length=4, null=True, verbose_name='Type')),
                ('direction', models.CharField(blank=True, choices=[('N', 'North'), ('W', 'West'), ('S', 'South'), ('E', 'East')], max_length=1, null=True, verbose_name='Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number')),
                ('number_additional', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.street')),
            ],
        ),
        migrations.CreateModel(
            name='AddressHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Effective date')),
                ('reason', models.CharField(choices=[('rebuilt_1921', 'Post-massacre rebuild (1921)'), ('urban_renewal', 'Urban Renewal'), ('idl_construction', 'I-244 / IDL construction'), ('street_renamed', 'Street renamed'), ('routine_renumbering', 'Routine renumbering'), ('destroyed', 'Destroyed'), ('new_construction', 'New construction'), ('other', 'Other')], max_length=32, verbose_name='Reason')),
                ('source_document', models.CharField(blank=True, max_length=255, verbose_name='Source document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('from_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_history_events', to='addresses.address')),
                ('to_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_history_events', to='addresses.address')),
            ],
            options={
                'indexes': [models.Index(fields=['effective_date'], name='addresses_a_effecti_3d1d17_idx'), models.Index(fields=['reason'], name='addresses_a_reason_c557e1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_address__isnull', False), ('to_address__isnull', False), _connector='OR'), name='address_history_has_at_least_one_endpoint')],
            },
        ),
    ]
