# Generated by Django 4.1.7 on 2023-04-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="number_additional",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
