# Generated by Django 4.2 on 2023-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ave", "Avenue"),
                    ("blvd", "Boulevard"),
                    ("st", "Street"),
                    ("pl", "Place"),
                ],
                default="st",
                max_length=4,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
