# Generated by Django 5.2.13 on 2026-04-20 05:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_earliest", models.DateTimeField(blank=True, null=True)),
                ("start_latest", models.DateTimeField(blank=True, null=True)),
                ("end_earliest", models.DateTimeField(blank=True, null=True)),
                ("end_latest", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("destruction_zone", "Destruction zone"),
                            ("rebuild_progression", "Rebuild progression"),
                            ("neighborhood_bound", "Neighborhood boundary"),
                            ("sanborn_area", "Sanborn map area"),
                            ("historical_building", "Historical building footprint"),
                            ("historical_road", "Historical road"),
                            ("poi_footprint", "Featured POI footprint"),
                            ("modern_building_footprint", "Modern building footprint"),
                            ("parcel", "Parcel (modern)"),
                            ("quarter_section", "PLSS quarter section"),
                            ("township", "PLSS township"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="Geometry"
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, verbose_name="Source")),
                (
                    "source_id",
                    models.CharField(blank=True, max_length=255, verbose_name="Source ID"),
                ),
                (
                    "properties",
                    models.JSONField(blank=True, default=dict, verbose_name="Properties"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Curated address linkage. Bulk imports leave null and query spatially.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_features",
                        to="addresses.address",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind"], name="overlays_ma_kind_ba0490_idx"),
                    models.Index(
                        fields=["source", "source_id"], name="overlays_ma_source_99c9b2_idx"
                    ),
                ],
            },
        ),
    ]
