# Generated by Django 5.2.13 on 2026-04-20 05:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_earliest', models.DateTimeField(blank=True, null=True)),
                ('start_latest', models.DateTimeField(blank=True, null=True)),
                ('end_earliest', models.DateTimeField(blank=True, null=True)),
                ('end_latest', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('kind', models.CharField(choices=[('destruction_zone', 'Destruction zone'), ('rebuild_progression', 'Rebuild progression'), ('neighborhood_bound', 'Neighborhood boundary'), ('sanborn_area', 'Sanborn map area'), ('other', 'Other')], max_length=32, verbose_name='Kind')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'indexes': [models.Index(fields=['kind'], name='overlays_hi_kind_7df69e_idx')],
            },
        ),
    ]
