# Generated by Django 5.2.13 on 2026-04-20 05:11

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.entity')),
                ('name_parsed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='EntityEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('name', models.CharField(max_length=120)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('canonical', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='entities.entity')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='entity_events', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_meta_canonical_events', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reverted', 'Reverted')], default='active', max_length=10, verbose_name='Status')),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('merged_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_event', to='entities.entity')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_merges_performed', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_merges_reverted', to=settings.AUTH_USER_MODEL)),
                ('surviving_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed_merges', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('name_parsed', models.BooleanField(default=False)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='person_events', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_parsed_events', to='entities.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='person_events', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proprietor_events', to='entities.business')),
                ('proprietor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='entities.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='business',
            name='proprietor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.person'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='person',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "entities_personevent" ("name_parsed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."name_parsed", _pgh_attach_context(), NOW(), \'insert\', NEW."entity_ptr_id"); RETURN NULL;', hash='1641c328d1176c5b373ff4472d9e80f07f931ce3', operation='INSERT', pgid='pgtrigger_insert_insert_9fbb5', table='entities_person', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='person',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name_parsed" IS DISTINCT FROM (NEW."name_parsed"))', func='INSERT INTO "entities_personevent" ("name_parsed", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."name_parsed", _pgh_attach_context(), NOW(), \'update\', NEW."entity_ptr_id"); RETURN NULL;', hash='da38940c2cd6b515a1ac34527cd5f8ecad4c5ccc', operation='UPDATE', pgid='pgtrigger_update_update_b17e9', table='entities_person', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entity',
            trigger=pgtrigger.compiler.Trigger(name='read_only_fields', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='d4e0a0bbb0dcded70bb0d1e8a6fe1cd484c9aca1', operation='UPDATE', pgid='pgtrigger_read_only_fields_d0075', table='entities_entity', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entity',
            trigger=pgtrigger.compiler.Trigger(name='protect_deletes', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;", hash='7e42d529581adb39ead3b90aeb5bcdcf0b010c17', operation='DELETE', pgid='pgtrigger_protect_deletes_0bd2b', table='entities_entity', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entity',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "entities_entityevent" ("canonical_id", "meta", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."canonical_id", NEW."meta", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='7905f49e580347421c3825e0ab1df91d4f1109e3', operation='INSERT', pgid='pgtrigger_insert_insert_10f03', table='entities_entity', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entity',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."canonical_id" IS DISTINCT FROM (NEW."canonical_id") OR OLD."meta" IS DISTINCT FROM (NEW."meta") OR OLD."name" IS DISTINCT FROM (NEW."name"))', func='INSERT INTO "entities_entityevent" ("canonical_id", "meta", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."canonical_id", NEW."meta", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='b9ee8b7f04c8c24c119b3abe61c58748b69a23da', operation='UPDATE', pgid='pgtrigger_update_update_1c1de', table='entities_entity', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='entitymerge',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('merged_entity',), name='only_one_active_merge_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='entitymerge',
            constraint=models.CheckConstraint(condition=models.Q(('surviving_entity', models.F('merged_entity')), _negated=True), name='cannot_merge_entity_into_itself'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='business',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "entities_businessevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "proprietor_id") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."entity_ptr_id", NEW."proprietor_id"); RETURN NULL;', hash='22be60c0c3ba1877fb9a982715582f74b0abb7c1', operation='INSERT', pgid='pgtrigger_insert_insert_01c5b', table='entities_business', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='business',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."proprietor_id" IS DISTINCT FROM (NEW."proprietor_id"))', func='INSERT INTO "entities_businessevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "proprietor_id") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."entity_ptr_id", NEW."proprietor_id"); RETURN NULL;', hash='8dca6d02c0b6eb213a3f2881a34d9dfb38729d46', operation='UPDATE', pgid='pgtrigger_update_update_1ff04', table='entities_business', when='AFTER')),
        ),
    ]
